[package]
name = "NicoNicoNi"
version = "0.1.0"
authors = ["Cody Kotichas <ckotichas@csu.fullerton.edu>"]
description="にっこにっこに〜"
license="MIT OR Apache-2.0"


[dependencies]
ears = "0.5.1"
base64 = "0.9.3"