[package]
name = "nico_nico_ni"
version = "0.1.1"
authors = ["Abby <i@abby.md>"]
description="にっこにっこにー♪あなたのハートににこにこにー♪笑顔届ける矢澤にこにこー♪にこにーって覚えてラブにこー♪"
license="MIT OR Apache-2.0"


[dependencies]
ears = "0.5.1"
base64 = "0.9.3"